# POST http://127.0.0.1:8000/auth/token/login/ HTTP/1.1
# content-type: application/json

# {"username": "nikki","password":"loki45"}


# POST http://127.0.0.1:8000/auth/token/login/ HTTP/1.1
# content-type: application/json

# {"username": "denisov","password":"loki45"}


# GET http://127.0.0.1:8000/api/v1/tasks/ HTTP/1.1
# Content-Type: application/json
# Authorization: token b3417cabdcde159b76a1b3be676bcfb6b5d4aa99


# POST  http://127.0.0.1:8000/api/v1/tasks/ HTTP/1.1
# Content-Type: application/json
# Authorization: token b3417cabdcde159b76a1b3be676bcfb6b5d4aa99

# {
#     "title": "post",
#     "content": "popost",
#     "workgroup": 3,
#     "workers": [
#         1
#     ]}


#post request to add comment
# POST http://127.0.0.1:8000/api/v1/task/3/comment/ HTTP/1.1
# Content-Type: application/json
# Authorization: token b3417cabdcde159b76a1b3be676bcfb6b5d4aa99

# {
#     "body": "yo-ho-ho",
#     "answer_to": 24
# }


GET http://127.0.0.1:8000/auth/users/me HTTP/1.1
Content-Type: application/json
Authorization: token 536476ddbd4889777441e4c587af2e6c2cc2c85f