# Generated by Django 4.2.6 on 2023-12-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_groupjoin_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользоватеworkли",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="workgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="accounts.workgroup",
            ),
        ),
    ]
