# Generated by Django 4.2.6 on 2024-01-02 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_invite_delete_groupjoin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="code",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="workgroup",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name="Joins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joins",
                        to="accounts.workgroup",
                    ),
                ),
            ],
        ),
    ]
