# Generated by Django 4.2.6 on 2024-01-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_invite_code_alter_workgroup_name_joins"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupJoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joins",
                        to="accounts.workgroup",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Invite",
            new_name="GroupInvite",
        ),
        migrations.DeleteModel(
            name="Joins",
        ),
    ]
