# Generated by Django 4.2.6 on 2023-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_taskcomment_answer_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Утверждено"),
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Завершено"),
        ),
    ]
