# Generated by Django 4.2.6 on 2023-11-19 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_approved_task_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Добавлено",
            ),
            preserve_default=False,
        ),
    ]
