# Generated by Django 4.2.6 on 2023-12-05 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_taskcomment_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задачу", "verbose_name_plural": "Задачи"},
        ),
    ]
